# Path to the solver source code
SRC = ../../src/
# Path to the problem source code
PROB = ./

# Header and souce for the model
MODELHDR =	$(PROB)CorridorModel.h

MODELSRC =	$(PROB)CorridorModel.cc

# Main file of solver
SOLVERMAIN = $(PROB)Solver.cc

# Main file of simulator
SIMULATORMAIN = $(PROB)CorridorSimulator.cc

include $(SRC)common.mk
